### ISSUE TITLE
Missing data for Generic Message. 

### ISSUE THREAD

**Issue by aakashbarot** [jun85664396/facebook-messenger-bot#1]
Hey Hi, 
I went through the implementation and it works awesome. 
I would be really grateful if you can provide the implementation for the generic message. 

In the model you are asking for Data from Generic message type, but in controller you are just sending 'sender' 
`res = FacebookBot.new.send_generic_message(sender)`
How do you provide data for structured message. Whats the format? 
Thanks a lot in advance.

**Comment by jun85664396** [comment]
Hello
sorry 'sender' is typo
please see this link! https://developers.facebook.com/docs/messenger-platform/send-api-reference#guidelines
